### ISSUE TITLE
NFS WRITE fail causes terminal script to hang indefinitely and blocks other attempts to access NFS-hosted filesystem

### ISSUE THREAD

**Issue by cbj4074** [winnfsd/winnfsd#24]
I just downloaded version 2.1.0, and I'm putting it through the paces in order to determine whether or not the primary show-stoppers (for my use-case, anyway) are still present in the binary.

The primary issue that I'm seeing with 2.1.0, which exists in earlier versions, is a "hanging" behavior whenever the `winnfsd.exe` daemon lacks write access to the exported mount point, on the Windows side.

Whenever writing to a specific file fails, regardless of the underlying reason, the NFS daemon (on the Windows side, `winnfsd.exe`) seems to hang for an unreasonably long time.

For example, I'm attempting to use Composer in a PHP project, and Composer lacks permission to the filesystem (on the Windows side) because the user as whom I am running `winnfsd.exe` also lacks write access to said directory, and here's what I see:

```
# composer install
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
[and then Composer hangs for a long, long time at this stage... ten minutes and counting]
```

When the hang occurs, other requests to `winnfsd.exe` seem to be "queued" or "blocked", *but*, every so often, other NFS events will be "allowed through" and processed, as evidenced in the daemon's logging output.

Here's what I see in the daemon's log output while this is happening:

```
[16:3:1] NFS ACCESS \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor  OK
[16:3:1] NFS ACCESS \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\composer  OK
[16:3:1] NFS ACCESS \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\symfony  OK
[16:3:1] NFS ACCESS \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\symfony\debug  OK
[16:3:1] NFS ACCESS \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\symfony\debug\Exception  OK
[16:3:1] NFS GETATTR \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\symfony\debug\Exception\FlattenException.php  OK
[16:3:1] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  fail
[16:3:1] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  fail
[16:3:1] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  fail
[16:4:1] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  fail
[16:4:1] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  fail
[16:4:1] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  fail
[16:4:1] NFS GETATTR \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\storage\logs\laravel.log  OK
[16:4:41] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\composer\installed.json  fail
[16:4:41] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\composer\installed.json  fail
[16:4:41] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\composer\installed.json  fail
[16:4:41] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\composer\installed.json  fail
[16:4:41] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\composer\installed.json  fail
```

It's not clear just how far apart these write attempts (and resultant failures) are occurring, as the timestamps seem oddly-formatted.

Regardless of the underlying reasons for which the Windows filesystem permissions do not allow for `winnfsd.exe` to execute `NFS WRITE` operations on the files/directories in question, such failures should not:

a.) tie-up other attempts to access the NFS-hosted filesystem
b.) cause terminal applications to hang indefinitely

All of this said, version 2.1.0 does seem to have cleared-up several other issues that I was seeing! So, this version is looking rather promising! Very fine work!

Afterthought: Is it possible that Composer is at fault here? I am curious to know how Composer responds when it lacks write-access when NFS is completely out of the picture. I'll test it out and post back.

**Comment by marcharding** [comment]
Should be easy to fix, i'll take a look at it.

**Comment by cbj4074** [comment]
@marcharding Thanks so much for the immediate reply and willingness to check it out!

To add to my previous thoughts, I double-checked the underlying filesystem, and there were some permission-related issues (the user as whom I was running `winnfsd.exe` lacked write access to directories to which Composer was attempting to write), but now I've fixed the permissions and I still see same type of failures occurring.

If I go to the Windows side and examine the Effective Permissions for the user as whom I am running `winnfsd.exe`, everything looks good:

Yet, writing still fails:

```
[16:31:28] NFS LOOKUP \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  NOENT
[16:31:28] NFS CREATE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  OK
[16:31:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:31:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:31:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:32:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:32:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:32:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:34:28] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:34:38] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:34:38] NFS WRITE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  fail
[16:34:38] NFS GETATTR \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  OK
```

What seems strange is that `winnfsd.exe` is able to *create* the file (which can be seen in the second line of the entries pasted just above). Here's the line again:

```
[16:31:28] NFS CREATE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\collections\caeb5296a54dff5634efd32bce1e33d9  OK
```

**Comment by marcharding** [comment]
Hm, i'm not quite sure what happens...

I really thought this was fixed with https://github.com/winnfsd/winnfsd/commit/5f096829df2112ef8d9c830cbf4617183cc84850 and https://github.com/winnfsd/winnfsd/commit/16fee7a5698ed61f3a67585702e915d87540b53b (as it now works for other users and composer install is also included in the testsuite, see https://github.com/winnfsd/winnfsd/blob/master/tests/bash/composer.sh. Additionally i also work on projects with quite big vendor folders without any problems)

Would you mind to test the version i linked here https://github.com/winnfsd/winnfsd/issues/22#issuecomment-230125433?

Also, can you upload the composer.json which fails? Does a simple `composer require monolog/monolog` (like in the testsuite) work?

**Comment by eXtreme** [comment]
@marcharding it may be a hint but I always used to enable "Run this program as administrator" option in properties of winnfsd.exe. I tested it now, and with this option disabled, nfs hangs for me when running `cache:clear`, and it looks something like this:

```
lots of logs spamming here
...
...
...
[9:33:43] NFS ACCESS \\?\C:\Users\Jacek\P1\var\cache\de_  OK
[9:33:43] NFS CREATE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  OK
[9:33:43] NFS SETATTR \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  OK
[9:33:43] NFS ACCESS \\?\C:\Users\Jacek\P1\var\cache\de_  OK
[9:33:43] NFS GETATTR \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  OK
[9:33:43] NFS ACCESS \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  OK
[9:33:43] NFS SETATTR \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  OK
[9:33:43] NFS WRITE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  OK
[9:33:43] NFS WRITE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml9RMBtv  fail
```

it hangs for ~1m, then continues to work but again fails later:

```
lots of logs spamming here
...
...
...
[9:36:0] NFS GETATTR \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS ACCESS \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS READ \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS READ \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS READ \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS READ \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS READ \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS READ \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS GETATTR \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS ACCESS \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS SETATTR \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS WRITE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS WRITE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
[9:36:0] NFS WRITE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  fail
[9:36:0] NFS WRITE \\?\C:\Users\Jacek\P1\var\cache\de_\ap_DevDebugProjectContainer.xml  OK
```

and it goes like

When I run winnfsd.exe as administrator, everything works fine.

**Comment by cbj4074** [comment]
Thanks @eXtreme ; I tried your suggestion to run `winnfsd.exe` as an Administrator, but it doesn't change the behavior I'm seeing.

@marcharding I tried the newer executable that you mentioned and it does indeed fix the hanging! With this version, the `NFS WRITE` attempt still fails, but it doesn't hang.

Now, Composer returns *immediately* with its own version of "permission denied", which is all I was hoping to see addressed. I may very well have some permission-related issue that is completely unrelated to `winnfsd`, and if/when I find it, I'll let other people know.

As far as I'm concerned, this issue is fixed in the alternate binary to which you linked! Please close the issue if you wish.

Thanks again for your willingness to help!

**Comment by marcharding** [comment]
I'd really like to fix this, but i can't reproduce it. I have zero problems, neither as administrator nor as a normal user.

@eXtreme did you use the latest binary (1.2.1ALPHA2, WinNFSd develop [91a3b37])? I just tried it with a fresh symfony installation. No problems there...

**Comment by eXtreme** [comment]
@marcharding yes, alpha2 from this comment: https://github.com/winnfsd/winnfsd/issues/22#issuecomment-230125433 
and it takes veeery long time to finish `cache:clear` for me, alpha1 works fine. I use `virtio-net` adapter as you suggested.

**Comment by eXtreme** [comment]
I tried to record a gif with time measurment (around 13s on alpha1) and several minutes on alpha2 but then winnfsd alpha2 crashed... 
Something is wrong there.

**Comment by cbj4074** [comment]
Yes, I may have spoken too soon with regard to the hanging behavior being fixed.

After further testing, I notice that the alpha2 version of `winnfsd` will fail very quickly if it attempts to write to a file *that is already present* on the filesystem and `NFS WRITE` fails. But if the file does not yet exist, the daemon still hangs for an excessive period of time.

With regard to write failures occurring when they shouldn't, here's what I'm observing:

```
# composer install
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing cartalyst/collections (dev-master cbb167c)
    Downloading: 100%
    Failed to download cartalyst/collections from dist: Failed to execute unzip '/var/www/clients/client2/web5/web/vendor/cartalyst/collections/ab00e7c9dbcea1b5d633ee1be4422c44' -d '/var/www/clients/client2/web5/web/vendor/composer/ab507453' && chmod -R u+w '/var/www/clients/client2/web5/web/vendor/composer/ab507453'

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /var/www/clients/client2/web5/web/vendor/cartalyst/collections/ab00e7c9dbcea1b5d633ee1be4422c44 may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of /var/www/clients/client2/web5/web/vendor/cartalyst/collections/ab00e7c9dbcea1b5d633ee1be4422c44 or
        /var/www/clients/client2/web5/web/vendor/cartalyst/collections/ab00e7c9dbcea1b5d633ee1be4422c44.zip, and cannot find /var/www/clients/client2/web5/web/vendor/cartalyst/collections/ab00e7c9dbcea1b5d633ee1be4422c44.ZIP, period.

    Now trying to download from source
  - Installing cartalyst/collections (dev-master cbb167c)
    Cloning cbb167c9a2f54c65130f58e0353fac7219e8ecba


  [RuntimeException]
  Failed to clone https://github.com/cartalyst/collections.git via https, ssh protocols, aborting.
  - https://github.com/cartalyst/collections.git
    Cloning into '/var/www/clients/client2/web5/web/vendor/cartalyst/collections'...
    error: /var/www/clients/client2/web5/web/vendor/cartalyst/collections/.git/hooks/pre-commit.sample: close error: Permission denied
    fatal: cannot copy '/usr/share/git-core/templates/hooks/pre-commit.sample' to '/var/www/clients/client2/web5/web/vendor/cartalyst/collections/.git/hooks/pre-commit.sample': Permission denied
  - git@github.com:cartalyst/collections.git
    Cloning into '/var/www/clients/client2/web5/web/vendor/cartalyst/collections'...
    error: /var/www/clients/client2/web5/web/vendor/cartalyst/collections/.git/hooks/pre-commit.sample: close error: Permission denied
    fatal: cannot copy '/usr/share/git-core/templates/hooks/pre-commit.sample' to '/var/www/clients/client2/web5/web/vendor/cartalyst/collections/.git/hooks/pre-commit.sample': Permission denied
```

If I try to copy the file in question to the destination in question manually, it still fails:

```
# cp /usr/share/git-core/templates/hooks/pre-commit.sample /var/www/clients/client2/web5/web/vendor/cartalyst/pre-commit.sample
cp: failed to close ‘/var/www/clients/client2/web5/web/vendor/cartalyst/pre-commit.sample’: Permission denied
```

Note the reason: `failed to close`. That's pretty unusual, and seems to point at a problem with the NFS daemon.

The `stat` output for the source file:

```
# stat /usr/share/git-core/templates/hooks/pre-commit.sample
  File: ‘/usr/share/git-core/templates/hooks/pre-commit.sample’
  Size: 1642            Blocks: 8          IO Block: 4096   regular file
Device: fc00h/64512d    Inode: 529413      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-07-05 18:26:05.691588642 -0400
Modify: 2016-03-21 11:15:36.000000000 -0400
Change: 2016-03-22 18:03:39.611677981 -0400
 Birth: -
```

And for the parent directory:

```
# stat /var/www/clients/client2/web5/web/vendor/cartalyst
  File: ‘/var/www/clients/client2/web5/web/vendor/cartalyst’
  Size: 0               Blocks: 0          IO Block: 32768  directory
Device: 1ch/28d Inode: 37          Links: 1
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-07-05 18:37:55.000000000 -0400
Modify: 2016-07-05 18:37:55.000000000 -0400
Change: 2016-07-05 18:37:55.000000000 -0400
 Birth: -
```

This does not seem to be a run-of-the-mill file-permissions issue. That said, it could be something on the Windows side that is not `winnfsd.exe` itself.

Another curious observation is that I'm able to create a file in the very same directory if I do it manually:

`echo 'Hello, world!' > /var/www/clients/client2/web5/web/vendor/cartalyst/hello-world.txt`

The file is created and I'm able to read the string.

The `winnfsd.exe` log reports success immediately:

```
[18:49:54] NFS CREATE \\?\C:\Users\Anon\Documents\Web\data-grid-quickstart\vendor\cartalyst\hello-world.txt  OK
```

Very strange. Any idea what could be causing this?

I should mention also that I am running `winnfsd.exe` on Windows 10 x64. Have you tried reproducing this on Windows 10, @marcharding ?

**Comment by cbj4074** [comment]
So, check it out: I just created a completely new, and limited-privilege user account in Windows, went through (what I feel like) are all the same steps, and it all works!!!

Next, I'll try to establish what's different in each case, which will hopefully lead us to a reproducible case.

I will also answer your other questions from earlier, @marcharding !

**Comment by cbj4074** [comment]
Just a quick update here.

The one thing that is starkly different between the environment in which `NFS WRITE` operations fail and hang and the environments in which it works as expected is the fact that the problematic system is running Ubuntu 14.04 LTS, whereas the working system is running Ubuntu 16.04 LTS.

I'm going to stand-up an Ubuntu 16.04 LTS system and configure it as similarly as possible to the failing system and see what happens... more soon!

**Comment by marcharding** [comment]
Just a quick question: are you using winnfsd via tcp or udp? (if you're not sure, check with `mount -v`)

I can reproduce this with tcp (but do not have a fix).

**Comment by cbj4074** [comment]
Indeed, I am using TCP:

```
192.168.56.1:/C/Users/Anon/Documents/Web/data-grid-quickstart on /var/www/clients/client2/web5/web type nfs (rw,noatime,nolock,bg,nfsvers=3,tcp,addr=192.168.56.1)
```
Brilliant! Switching to UDP fixes the issue!

I think you just identified precisely what is different between my Homestead Vagrant environment and my hand-installed Ubuntu installation: I was using `tcp` in the mount line in `/etc/fstab`.

You, sir, are the hero of the day!

If it works with UDP, then I am happy as a clam. If there is an eventual fix for TCP, then wonderful. :)

Thank you so much for seeing this through and pinning-down the issue!

**Comment by marcharding** [comment]
FYI, TCP fix incoming sometime this/next week (works even better with composer, even cases that failed before now work for me).

**Comment by marcharding** [comment]
See https://github.com/winnfsd/winnfsd/issues/22#issuecomment-232504404

**Comment by marcharding** [comment]
I'm closing this because it should be fixed in 2.2.0 (even when using tcp).

If the problem still occurs please reopen this.
